version: '2'
services:
  api:
    volumes:
      - .:/tetra
    command: |
      bash -c "export PYTHONUNBUFFERED=1 && gunicorn --reload -t 120 --bind 0.0.0.0:7374 --access-logfile - tetra.app:application"
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    volumes:
      - ./ui/:/work
      - /work/node_modules
      - /work/dist
