version: '2'
services:
  api:
    image: mendersoftware/mantra-api:master
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mantra-api
    depends_on:
      - db
    links:
      - db
    command: |
      bash -c "export PYTHONUNBUFFERED=1 && gunicorn -t 120 --bind 0.0.0.0:7374 --access-logfile - tetra.app:application"
    ports:
      - "7374:7374"
  db:
    image: bitnami/postgresql:12.2.0
    container_name: mantra-db
    ports:
      # note: exposing port 5432 here causes issues in travis builds
      - "5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mantra-db
  ui:
    image: mendersoftware/mantra-ui:master
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: mantra-ui
    ports:
      - "8080:80"
    depends_on:
      - api
  gateway:
    image: nginx:stable-alpine
    container_name: mantra-gateway
    entrypoint: >
      /bin/sh -c 'echo "
      events {}
      http {
        server {
          location / {
            proxy_max_temp_file_size 128m;
            proxy_buffers 16 16k;
            proxy_buffer_size 16k;
            proxy_pass http://ui:80;
          }
          location ~* /api/(.*) {
            proxy_max_temp_file_size 128m;
            proxy_buffers 16 16k;
            proxy_buffer_size 16k;
            rewrite ^/api(.*)$$ \$$1 break;
            proxy_pass http://api:7374;
          }
        }
      }" > /etc/nginx/nginx.conf && nginx -g "daemon off;"
      '
    ports:
      # The HTTP port
      - "80:80"
    depends_on:
      - ui
      - api
